repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: ^dist/.*$
      - id: end-of-file-fixer
        exclude: ^dist/.*$
      - id: trailing-whitespace
        exclude: ^dist/.*$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: ^dist/.*$
