name: junit2otel-collector
desription: GitHub Action to process and send to a OpenTelemetry service a JUnit result file stored as artifact on a workflow run.
inputs:
  reportName:
    description: Name of the JUnit archived file. If there are multiple JUnit files it should be a `.zip` file.
    required: false
    default: junit-report.xml
  workflowRunId:
    description: Id of the workflow run where the JUnit files are archived.
    required: false
    default: ${{ github.event.workflow_run.id }}
  owner:
    description: Owner of the repository we want ro process.
    required: false
    default: ${{ github.event.workflow_run.head_repository.owner.login }}
  repo:
    description: The repository we want ro process.
    required: false
    default: ${{ github.event.workflow_run.head_repository.name }}
runs:
  using: "composite"
  steps:
    - name: Download JUnit Artifact
      id: download-report
      uses: actions/github-script@v6.3.3
      with:
        script: |
          const repo = {
            owner: '${{ inputs.owner }}',
            repo: '${{ inputs.repo }}',
            workflowRunId: '${{ inputs.workflowRunId }},
            reportName: '${{ inputs.reportName }}'
          }
          const script = require('./script.js')
          script.downloadReport(repo)
    - name: Uncompress files
      # bash is in all runners types
      shell: bash
      # 7zip is in all runners types.
      run: |
        7z x -o ${{ steps.download-report.outputs.report-file }}
    - name: Process JUnit files
      shell: bash
      run: |
        for report in $(find ${{ steps.download-report.outputs.tempdir }} -name '*.xml');
        do
          echo "Procesing ${report}"
        done
