---
name: Test

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      - id: test-execution
        run: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results.xml
          path: junit.xml
      - uses: ./
        with:
          reportName: ${{ steps.test-execution.outputs.reportName }}
          workflowRunId: ${{ steps.test-execution.outputs.workflowRunId }}
          owner: ${{ steps.test-execution.outputs.owner }}
          repo: ${{ steps.test-execution.outputs.repo }}
